### ISSUE TITLE
Please Help

### ISSUE THREAD

**Issue by Nichenstein** [gibbed/DemonsSoulsDebug#3]
###  Can t find boot.elf anywere

**Comment by gibbed** [comment]
The instructions clearly state how to obtain it. What's the issue?

**Comment by Nichenstein** [comment]
Yes the instructions are straight foreword. But i tried 7 times and my RPCS3 never creates an boot.elf in my data\BLUS30443\

DS Version BLUS30443

RPCS3 v0.0.6-8410 Alpha [2019-07-22]

**Comment by gibbed** [comment]
Ah, it's possible RPCS3 has changed its behavior regarding saving decrypted executables. I'll look into it.

**Comment by Nichenstein** [comment]
Thank You !

**Comment by Nichenstein** [comment]
Any luck?

**Comment by SonofUgly** [comment]
Yeah it doesn't save boot.elf anymore since https://github.com/RPCS3/rpcs3/pull/5453. The build before that was 0.0.5-7715 (any build before that will also work), which you can download here: https://rpcs3.net/compatibility?b

**Comment by gibbed** [comment]
Newer builds of rpcs3 now has a menu option for decrypting PS3 executables. Documentation fixed via ec8d6b0.
